
/**
 * A really useful Exception for the case when the result generated by the classifier is not 
 * expected (it's a big problem ,big enough to use a exception to warn developer and users)
 *
 * @author Fu Zhang, Michael Owen Jones, A K M Naharul Hayat and Noyan Raquib
 * @version 30/03/2018
 */
public class ClassifierNotConfigeredProperlyException extends Exception
{
    

    /**
     * Constructor for objects of class ClassifierNotConfigeredProperlyException
     */
    public ClassifierNotConfigeredProperlyException()
    {
        super("There is a problem in Classifier, Mainly because the traning process have errors, Please contact developer ");
    }

    
}

